version: '3.8'

services:
  influx: 
    container_name: influx
    hostname: influx
    image: influxdb:2.0
    # restart: always
    volumes:
      - ./volumes/data/influx:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=ICEA
      - DOCKER_INFLUXDB_INIT_BUCKET=cps
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    networks:
      - app
    ports:
      - 8086:8086

  mongo:
    container_name: mongo
    user: '1000:1000'
    hostname: mongo
    # restart: always
    image: mongo:6
    volumes:
      - ./volumes/data/mongo:/data/db
    networks:
      - app
    ports:
      - 27017:27017
      
  mosquitto:
    container_name: mqtt
    hostname: mqtt
    networks:
      - app
    image: eclipse-mosquitto:2
    volumes:
      - ./volumes/etc/mqtt/config/:/mosquitto/config/
      - ./volumes/etc/mqtt/log/:/mosquitto/log/
      - ./volumes/data/mqtt:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
networks:
  app:
    driver: bridge
